import { LogicalPath, WORKSPACE_ROOT_DIRNAME } from "@verchestra/domain";

import { WorkspaceScanError } from "../scanner/scanner-primitives.ts";
import {
  PROBE_ENGINE_TEMPLATES,
  PROBE_SCAFFOLD_ENGINES,
  type ProbeEngineTemplate,
  type ProbeScaffoldEngine
} from "./probe-scaffold-engines.ts";

export { PROBE_SCAFFOLD_ENGINES, type ProbeScaffoldEngine };

export const PROBE_CONTRACT_VERSION = 1 as const;
export const PROBE_SCAFFOLD_LANGUAGES = Object.freeze(["typescript"] as const);
export const PROBE_DRIVER_TODO_CODE = "VES_PROBE_DRIVER_TODO" as const;
export type ProbeScaffoldLanguage = (typeof PROBE_SCAFFOLD_LANGUAGES)[number];

// invariant: SafeInitService only writes inside the control metadata root, so
// the scaffold directory is confined to one subtree of it. Lowercase segments
// without a leading dot keep it clear of the managed ignored directories and
// of the init staging directories, on case-insensitive filesystems too.
const PROBE_ROOT = `${WORKSPACE_ROOT_DIRNAME}/probes`;
const PROBE_SEGMENT = /^[a-z0-9][a-z0-9_-]{0,62}$/u;
const MAXIMUM_PROBE_DEPTH = 4;

export function isProbeScaffoldEngine(value: string): value is ProbeScaffoldEngine {
  return (PROBE_SCAFFOLD_ENGINES as readonly string[]).includes(value);
}

export function defaultProbeScaffoldDirectory(engine: ProbeScaffoldEngine): string {
  return `${PROBE_ROOT}/${engine}`;
}

export function isProbeScaffoldDirectory(value: string): boolean {
  try {
    LogicalPath.parse(value);
  } catch {
    return false;
  }
  if (!value.startsWith(`${PROBE_ROOT}/`)) return false;
  const segments = value.slice(PROBE_ROOT.length + 1).split("/");
  return segments.length <= MAXIMUM_PROBE_DEPTH && segments.every((segment) => PROBE_SEGMENT.test(segment));
}

const HEADER = (engine: ProbeScaffoldEngine) =>
  `// Generated by \`vestra init --probe-engine ${engine}\` for Verchestra probe contract ${PROBE_CONTRACT_VERSION}.`;

function contractFile(engine: ProbeScaffoldEngine, template: ProbeEngineTemplate): string {
  return `${HEADER(engine)}
// This is a copy of the published ${template.title} connection port and its
// supporting types. Do not edit it: it pins the contract your connection
// implements and the conformance kit checks.

export const PROBE_CONTRACT = Object.freeze({ engine: "${engine}", version: ${PROBE_CONTRACT_VERSION} } as const);

export type UnknownRecord = Readonly<Record<string, unknown>>;
export type Classification = "public" | "internal" | "confidential" | "restricted" | "secret";

${template.contractTypes}
`;
}

// invariant: mirrors how the formatter lays out an import, so generated files
// stay stable under the team's own formatting. Every generated import goes
// through here, which also keeps literal import lines out of this module's
// source, where the repository's textual import-closure guards would read them.
function importStatement(head: string, names: readonly string[], from: string): string {
  const sorted = [...new Set(names)].sort();
  const single = `import ${head}{ ${sorted.join(", ")} } from "${from}";`;
  if (single.length <= 120) return single;
  return `import ${head}{\n${sorted.map((name) => `  ${name}`).join(",\n")}\n} from "${from}";`;
}

function connectionFile(engine: ProbeScaffoldEngine, template: ProbeEngineTemplate): string {
  return `${HEADER(engine)}
// TODO(driver): choose the ${template.driverChoice} this connection wraps, for
// example ${template.driverPackages}.
// Verchestra never adds a dependency: install your choice yourself, then pass
// an already configured client into a constructor you add here. Keep
// credentials out of this file.

${importStatement("type ", [...template.stubImports, "UnknownRecord"], "./contract.mts")}

export const PROBE_DRIVER_TODO = "${PROBE_DRIVER_TODO_CODE}";

// Delete this class once no method below throws it.
export class ProbeDriverTodoError extends Error {
  readonly code = PROBE_DRIVER_TODO;
  readonly method: string;

  constructor(method: string) {
    super(\`TODO(driver): ${template.connectionClass}.\${method} is not implemented\`);
    this.name = "ProbeDriverTodoError";
    this.method = method;
  }
}

export class ${template.connectionClass} implements ${template.port} {
${template.stubMethods}
}
`;
}

function targetInterface(template: ProbeEngineTemplate): string {
  const request =
    template.target === "document"
      ? "  readonly command: UnknownRecord;\n"
      : "  readonly statement: string;\n  readonly parameters: readonly unknown[];\n";
  return `export interface ConformanceTarget {
  readonly databaseId: string;
  readonly kind: "select" | "introspect";
${request}  readonly objects: readonly { readonly schema: string; readonly name: string; readonly type: "table" | "catalog" }[];
  readonly functions: readonly string[];
  readonly bounds?: ConformanceBounds;
}`;
}

const PRODUCT_CHECK = `
function requireProduct(observed: string, expected: string): void {
  if (observed !== expected) {
    fail("VES_PROBE_KIT_PRODUCT_MISMATCH", "The connection reports a different database product");
  }
}
`;

function kitFile(engine: ProbeScaffoldEngine, template: ProbeEngineTemplate): string {
  const classifications = template.target === "document" ? "[]" : 'target.parameters.map(() => "internal" as const)';
  const rowLimitArgument = template.boundedStream ? ", bounds.rowLimit" : "";
  return `${HEADER(engine)}
// The port-level conformance kit for probe contract ${PROBE_CONTRACT_VERSION}. It drives your connection
// through the exact sequence the Verchestra ${template.title} adapter uses and
// applies the same read-only verdicts. Do not edit it.

${importStatement(
  "",
  ["PROBE_CONTRACT", ...[...template.kitImports, "UnknownRecord"].map((name) => `type ${name}`)],
  "./contract.mts"
)}

export class ConformanceKitFailure extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = "ConformanceKitFailure";
    this.code = code;
  }
}

export interface ConformanceBounds {
  readonly timeoutMs: number;
  readonly rowLimit: number;
}

${targetInterface(template)}

export interface ConformanceReport {
  readonly engine: typeof PROBE_CONTRACT.engine;
  readonly contractVersion: typeof PROBE_CONTRACT.version;
  readonly rowCount: number;
}

export const DEFAULT_CONFORMANCE_BOUNDS: ConformanceBounds = Object.freeze({ timeoutMs: 5_000, rowLimit: 100 });

function fail(code: string, message: string): never {
  throw new ConformanceKitFailure(code, message);
}

export function conformancePlan(target: ConformanceTarget, bounds: ConformanceBounds): ${template.plan} {
  return Object.freeze({
${template.kitPlanExtras}    databaseId: target.databaseId,
    planDigest: "sha256:${"0".repeat(64)}",
    operation: Object.freeze({
      kind: target.kind,
      statementCount: 1,
      protectedRequestRef: "protected-request:conformance-kit",
      objects: target.objects,
      functions: target.functions,
      parameterClassifications: ${classifications}
    }),
    bounds: Object.freeze(${template.kitBounds})
  });
}

function requireDatabase(observed: string, plan: { readonly databaseId: string }): void {
  if (observed !== plan.databaseId) {
    fail("VES_PROBE_KIT_IDENTITY_MISMATCH", "The connection reports a different database than the plan names");
  }
}
${template.kitChecks.includes("requireProduct(") ? PRODUCT_CHECK : ""}
function requireReadOnlyPrincipal(readOnly: boolean): void {
  if (!readOnly) {
    fail("VES_PROBE_KIT_PRINCIPAL_NOT_READ_ONLY", "The connected principal holds write or administrative authority");
  }
}

function requireReadOnlySession(readOnly: boolean): void {
  if (!readOnly) fail("VES_PROBE_KIT_SESSION_NOT_READ_ONLY", "The session did not prove itself read-only");
}

${template.kitChecks}

async function countRows(rows: AsyncIterable<UnknownRecord>, rowLimit: number): Promise<number> {
  let rowCount = 0;
  for await (const row of rows) {
    if (typeof row !== "object" || row === null || Array.isArray(row)) {
      fail("VES_PROBE_KIT_ROW_INVALID", "The connection streamed a row that is not a record");
    }
    rowCount += 1;
    if (rowCount > rowLimit) {
      fail("VES_PROBE_KIT_ROW_LIMIT_EXCEEDED", "The connection streamed more rows than the plan allows");
    }
  }
  return rowCount;
}

export async function runConformanceKit(
  connection: ${template.port},
  target: ConformanceTarget
): Promise<ConformanceReport> {
  const bounds = target.bounds ?? DEFAULT_CONFORMANCE_BOUNDS;
  const plan = conformancePlan(target, bounds);
  let released = false;
  try {
    await verifyPrincipal(connection, plan);
    await configureSession(connection, plan);
    const controller = new AbortController();
    const rows = streamProbe(connection, target, controller.signal${rowLimitArgument});
    const rowCount = await countRows(rows, bounds.rowLimit);
    await connection.cancel();
    await connection.terminate();
    released = true;
    return Object.freeze({ engine: PROBE_CONTRACT.engine, contractVersion: PROBE_CONTRACT.version, rowCount });
  } finally {
    if (!released) await connection.terminate().catch(() => undefined);
  }
}
`;
}

function conformanceTestFile(engine: ProbeScaffoldEngine, template: ProbeEngineTemplate): string {
  return `${HEADER(engine)}
// Run it with \`node --test\`. It fails with ${PROBE_DRIVER_TODO_CODE} until every
// TODO(driver) in connection.mts is implemented; that failure is intended.

import assert from "node:assert/strict";
import { test } from "node:test";

${importStatement("", ["runConformanceKit", "type ConformanceTarget"], "./conformance-kit.mts")}
${importStatement("", [template.connectionClass], "./connection.mts")}

// TODO(target): point this at a disposable database your CI provisions. Your
// connection must report the same databaseId in inspectPrincipal.
const target: ConformanceTarget = ${template.defaultTarget};

test("${engine} probe connection conforms to Verchestra probe contract ${PROBE_CONTRACT_VERSION}", async () => {
  const report = await runConformanceKit(new ${template.connectionClass}(), target);
  assert.equal(report.engine, "${engine}");
  assert.equal(report.contractVersion, ${PROBE_CONTRACT_VERSION});
});
`;
}

function readmeFile(engine: ProbeScaffoldEngine, template: ProbeEngineTemplate): string {
  return `# ${template.title} probe scaffold

Generated by \`vestra init --probe-engine ${engine}\` for Verchestra probe
contract ${PROBE_CONTRACT_VERSION}. The generator made no network call, used no AI, and added no
dependency to this repository.

## Files

- \`contract.mts\`: a copy of the published ${template.title} connection port. Do not
  edit it.
- \`connection.mts\`: \`${template.connectionClass}\`, your implementation of the
  port.
- \`conformance-kit.mts\`: the port-level conformance kit for contract ${PROBE_CONTRACT_VERSION}. Do not
  edit it.
- \`conformance.test.mts\`: runs the kit against your connection. Edit only its
  \`TODO(target)\`.

## Finish the scaffold

1. Choose the ${template.driverChoice}, for example ${template.driverPackages}.
   Installing it is your decision; Verchestra does not do it for you.
2. Replace every \`TODO(driver)\` in \`connection.mts\`, then delete
   \`ProbeDriverTodoError\`.
3. Point the \`TODO(target)\` in \`conformance.test.mts\` at a disposable
   database your CI provisions, reached read-only.

## Run the kit

\`\`\`bash
node --test conformance.test.mts
\`\`\`

Run it from this directory with a Node release that strips TypeScript types
natively (22.18 or later, or 23.6 or later). Until step 2 is done the run fails
with \`${PROBE_DRIVER_TODO_CODE}\`. That failure is intended: the kit never passes
against an unimplemented connection. Every other failure carries a
\`VES_PROBE_KIT_*\` code that names the contract obligation your connection
broke.

## Typecheck

The files are ES modules (\`.mts\`) that import each other with explicit
\`.mts\` extensions, so they run the same whatever your \`package.json\`
\`type\` is. Typecheck them with \`allowImportingTsExtensions\` (or
\`rewriteRelativeImportExtensions\`) and the Node type definitions
(\`@types/node\`) in your TypeScript configuration.

## Keep it verified

Commit this directory once and run the kit in your own CI on every change, on
every database engine upgrade, and on every contract version bump.

## Completing it with AI

This scaffold is complete without AI. If you want a Driver to fill in the
TODOs, run that as a normal Verchestra delivery task, with gates, review, and a
commit, once the governed task command is available in your release. The AI
only proposes changes in your workspace.
`;
}

export interface ProbeScaffoldInput {
  readonly engine: ProbeScaffoldEngine;
  readonly language: ProbeScaffoldLanguage;
  readonly directory: string;
  readonly contractVersion?: typeof PROBE_CONTRACT_VERSION;
}

const FILES: readonly (readonly [string, (engine: ProbeScaffoldEngine, template: ProbeEngineTemplate) => string])[] =
  Object.freeze([
    ["README.md", readmeFile],
    ["conformance-kit.mts", kitFile],
    ["conformance.test.mts", conformanceTestFile],
    ["connection.mts", connectionFile],
    ["contract.mts", contractFile]
  ]);

// invariant: the output depends only on (engine, contract version) and the
// directory it is placed in. It carries no timestamp and no product version,
// every file ends with one LF and contains no CR, and keys are sorted.
export function buildProbeScaffoldFiles(input: ProbeScaffoldInput): Readonly<Record<string, string>> {
  if (!isProbeScaffoldEngine(input.engine))
    throw new WorkspaceScanError("VES_INIT_INPUT_INVALID", "Probe engine is not supported");
  if (!(PROBE_SCAFFOLD_LANGUAGES as readonly string[]).includes(input.language))
    throw new WorkspaceScanError("VES_INIT_INPUT_INVALID", "Probe language is not supported");
  if ((input.contractVersion ?? PROBE_CONTRACT_VERSION) !== PROBE_CONTRACT_VERSION)
    throw new WorkspaceScanError("VES_INIT_INPUT_INVALID", "Probe contract version is not supported");
  if (!isProbeScaffoldDirectory(input.directory))
    throw new WorkspaceScanError("VES_INIT_INPUT_INVALID", "Probe directory is outside the probe root");
  const template = PROBE_ENGINE_TEMPLATES[input.engine];
  const files: Record<string, string> = {};
  for (const [name, render] of FILES) files[`${input.directory}/${name}`] = render(input.engine, template);
  return Object.freeze(files);
}
