import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterEach, test } from "node:test";

import {
  SafeInitService,
  buildCanonicalInitFiles,
  buildProbeScaffoldFiles
} from "../../packages/workspace/src/index.ts";
import {
  byteSnapshot,
  cleanupScannerRoots,
  git,
  initRepository,
  scannerRoot
} from "../helpers/workspace-scanner-fixture.mjs";

afterEach(cleanupScannerRoots);

const PROBE_DIRECTORY = ".verchestra/probes/postgresql";
const probe = () =>
  buildProbeScaffoldFiles({ engine: "postgresql", language: "typescript", directory: PROBE_DIRECTORY });
const files = () => ({
  ...buildCanonicalInitFiles({
    workspaceId: "workspace_018f0b6d-7b1a-7abc-8def-0123456789ab",
    displayName: "Probe Workspace",
    placementMode: "centralized",
    generatorVersion: "1.0.0"
  }),
  ...probe()
});

test("a probe scaffold preview lists every scaffold file as a create and writes zero bytes", async () => {
  const root = await scannerRoot();
  await initRepository(root);
  const before = await byteSnapshot(root);
  const preview = await new SafeInitService().preview({ controlRoot: root, files: files() });
  const probeChanges = preview.changes.filter((change) => change.logicalPath.startsWith(`${PROBE_DIRECTORY}/`));
  assert.deepEqual(
    probeChanges.map((change) => [change.logicalPath, change.action, change.expectedDigest]),
    Object.keys(probe()).map((path) => [path, "create", null])
  );
  assert.deepEqual(await byteSnapshot(root), before);
});

test("applying the scaffold writes the generated bytes, records ownership, and exposes the files to Git", async () => {
  const root = await scannerRoot();
  await initRepository(root);
  const service = new SafeInitService();
  const preview = await service.preview({ controlRoot: root, files: files() });
  const receipt = await service.apply(preview);
  assert.equal(receipt.changed, preview.changes.length);
  assert.equal(receipt.changed, 12);
  for (const [path, content] of Object.entries(probe())) {
    assert.equal(await readFile(join(root, ...path.split("/")), "utf8"), content);
  }
  const manifest = JSON.parse(await readFile(join(root, ".verchestra", "generated-manifest.json"), "utf8"));
  const owned = manifest.files.filter((entry) => entry.logicalPath.startsWith(`${PROBE_DIRECTORY}/`));
  assert.deepEqual(
    owned.map((entry) => [
      entry.logicalPath,
      entry.lifecyclePolicy,
      /^sha256:[a-f0-9]{64}$/u.test(entry.contentDigest)
    ]),
    Object.keys(probe()).map((path) => [path, "tracked", true])
  );
  const untracked = git(root, "ls-files", "--others", "--exclude-standard").split("\n");
  for (const path of Object.keys(probe())) assert.ok(untracked.includes(path), path);
  assert.equal(untracked.includes("package.json"), false);
  const packageJson = await readFile(join(root, "package.json"), "utf8");
  assert.equal(packageJson, '{"name":"fixture","private":true}\n');
});

test("repeating the identical scaffold init is a no-op", async () => {
  const root = await scannerRoot();
  await initRepository(root);
  const service = new SafeInitService();
  await service.apply(await service.preview({ controlRoot: root, files: files() }));
  const snapshot = await byteSnapshot(root);
  const second = await service.preview({ controlRoot: root, files: files() });
  assert.deepEqual(second.changes, []);
  assert.deepEqual(await service.apply(second), { planId: second.planId, changed: 0 });
  assert.deepEqual(await byteSnapshot(root), snapshot);
});

test("a scaffold the team has already filled in is never overwritten", async () => {
  const root = await scannerRoot();
  await initRepository(root);
  const service = new SafeInitService();
  await service.apply(await service.preview({ controlRoot: root, files: files() }));
  const connection = join(root, ...PROBE_DIRECTORY.split("/"), "connection.mts");
  await writeFile(connection, "// the team's real driver code\n", "utf8");
  const snapshot = await byteSnapshot(root);
  await assert.rejects(
    service.preview({ controlRoot: root, files: files() }),
    (error) => error.code === "VES_INIT_TARGET_CONFLICT"
  );
  assert.deepEqual(await byteSnapshot(root), snapshot);
});
