import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { test } from "node:test";

import ts from "typescript";

import {
  PROBE_CONTRACT_VERSION,
  PROBE_DRIVER_TODO_CODE,
  PROBE_SCAFFOLD_ENGINES,
  buildProbeScaffoldFiles,
  defaultProbeScaffoldDirectory,
  isProbeScaffoldDirectory
} from "../../packages/workspace/src/index.ts";

const FILE_NAMES = ["README.md", "conformance-kit.mts", "conformance.test.mts", "connection.mts", "contract.mts"];
const repositoryVersion = JSON.parse(readFileSync(new URL("../../package.json", import.meta.url), "utf8")).version;

const build = (engine, directory = defaultProbeScaffoldDirectory(engine)) =>
  buildProbeScaffoldFiles({ engine, language: "typescript", directory });

// invariant: one digest per (engine, contract version 1). A template change
// that alters generated bytes must update this table in the same change, so
// teams never receive silently different output for the same contract version.
const CONTRACT_1_DIGESTS = Object.freeze({
  postgresql: "b6936e4e7103af085f61fc5cbe2241134d48c7e2f3a458264e1043262b87f8a0",
  mysql: "d22a377009592408218af146e2e642ba31886f93bf48c6de1ede3dee67b4aee6",
  mariadb: "aa760e205ad019317837a5a107e97f0357853b22d44402933414dc513da7df39",
  sqlserver: "ae4ee1f61bf0b3d1fe590433cf05d05949ae73de9c6afd81b767e989d5899588",
  "sap-ase": "dd9d4d8aa943775477539232002995c29b60ee75540a058be4eb2885272855ca",
  oracle: "28c9d96173da74f17f8f71e72e3e569a91bde5fe9f6ad09979a80f563c75cb8a",
  sqlite: "5453aa4b1f74367efec9c8f2bd74584b51c6518a0eb749efc5cca306f700df0c",
  mongodb: "fc3a1207aab412a3c6c6f64b4aaa2682e4012380406e2900f1b59a22cd6c061a"
});

function contentDigest(files) {
  const hash = createHash("sha256");
  for (const [path, content] of Object.entries(files)) hash.update(`${path.split("/").pop()}\0${content}\0`);
  return hash.digest("hex");
}

test("the scaffold covers every published engine, including both MySQL-family engines", () => {
  assert.deepEqual(
    [...PROBE_SCAFFOLD_ENGINES],
    ["postgresql", "mysql", "mariadb", "sqlserver", "sap-ase", "oracle", "sqlite", "mongodb"]
  );
  assert.deepEqual(Object.keys(CONTRACT_1_DIGESTS), [...PROBE_SCAFFOLD_ENGINES]);
  assert.equal(PROBE_CONTRACT_VERSION, 1);
});

for (const engine of PROBE_SCAFFOLD_ENGINES) {
  test(`${engine}: two generations are byte-identical and match the contract 1 digest`, () => {
    const first = build(engine);
    const second = build(engine);
    assert.deepEqual(Object.keys(first), Object.keys(second));
    for (const path of Object.keys(first)) {
      assert.equal(Buffer.compare(Buffer.from(first[path], "utf8"), Buffer.from(second[path], "utf8")), 0, path);
    }
    assert.equal(contentDigest(first), CONTRACT_1_DIGESTS[engine]);
  });

  test(`${engine}: files are sorted, LF-only, ASCII, and free of time or release identity`, () => {
    const files = build(engine);
    const directory = defaultProbeScaffoldDirectory(engine);
    assert.equal(directory, `.verchestra/probes/${engine}`);
    assert.deepEqual(
      Object.keys(files),
      FILE_NAMES.map((name) => `${directory}/${name}`)
    );
    for (const [path, content] of Object.entries(files)) {
      assert.equal(content.endsWith("\n"), true, path);
      assert.equal(content.endsWith("\n\n"), false, path);
      assert.equal(content.includes("\r"), false, path);
      assert.equal(/[^\x0a\x20-\x7e]/u.test(content), false, `${path} holds a non-ASCII or control byte`);
      assert.equal(/[ \t]$/mu.test(content), false, `${path} has trailing whitespace`);
      assert.equal(content.includes(repositoryVersion), false, `${path} embeds the product version`);
      assert.equal(/\b20\d\d-\d\d-\d\d/u.test(content), false, `${path} embeds a date`);
    }
  });

  test(`${engine}: the directory changes only the paths, never the bytes`, () => {
    const standard = build(engine);
    const custom = build(engine, ".verchestra/probes/orders-db/primary");
    assert.deepEqual(Object.values(custom), Object.values(standard));
    assert.deepEqual(
      Object.keys(custom).map((path) => path.split("/").pop()),
      FILE_NAMES
    );
  });

  test(`${engine}: the connection throws a stable TODO(driver) code and adds no dependency`, () => {
    const files = build(engine);
    const directory = defaultProbeScaffoldDirectory(engine);
    const connection = files[`${directory}/connection.mts`];
    assert.match(connection, /\/\/ TODO\(driver\): choose the /u);
    assert.ok(connection.includes(`export const PROBE_DRIVER_TODO = "${PROBE_DRIVER_TODO_CODE}";`));
    assert.ok((connection.match(/throw new ProbeDriverTodoError\(/gu) ?? []).length >= 5);
    assert.equal((connection.match(/TODO\(driver\)/gu) ?? []).length >= 6, true);
    assert.match(files[`${directory}/conformance.test.mts`], /\/\/ TODO\(target\):/u);
    for (const path of Object.keys(files)) assert.doesNotMatch(path, /package\.json|lock/u);
    const imports = Object.values(files)
      .flatMap((content) => [...content.matchAll(/^import .* from "([^"]+)";$|^\} from "([^"]+)";$/gmu)])
      .map((match) => match[1] ?? match[2]);
    assert.ok(imports.length >= 5);
    for (const specifier of imports) assert.match(specifier, /^(?:\.\/[a-z-.]+\.mts|node:[a-z/]+)$/u);
  });
}

test("probe directories are confined to lowercase segments under .verchestra/probes/", () => {
  for (const accepted of [
    ".verchestra/probes/postgresql",
    ".verchestra/probes/orders-db",
    ".verchestra/probes/a/b/c/d"
  ])
    assert.equal(isProbeScaffoldDirectory(accepted), true, accepted);
  for (const refused of [
    ".verchestra/probes",
    ".verchestra/probes/",
    ".verchestra/probes/../workspace.yaml",
    ".verchestra/probes/./postgresql",
    ".verchestra/probes/.staging-x",
    ".verchestra/probes/Orders",
    ".verchestra/probes/a/b/c/d/e",
    ".verchestra/.secrets/postgresql",
    ".verchestra/postgresql",
    "src/probes/postgresql",
    "/tmp/probes",
    ".verchestra\\probes\\postgresql",
    ".verchestra/probes/con"
  ])
    assert.equal(isProbeScaffoldDirectory(refused), false, refused);
});

test("the generator refuses an unknown engine, language, contract version, or directory", () => {
  const valid = { engine: "postgresql", language: "typescript", directory: ".verchestra/probes/postgresql" };
  for (const override of [
    { engine: "db2" },
    { language: "python" },
    { contractVersion: 2 },
    { directory: "src/probes" },
    { directory: ".verchestra/probes/../../etc" }
  ]) {
    assert.throws(
      () => buildProbeScaffoldFiles({ ...valid, ...override }),
      (error) => error.code === "VES_INIT_INPUT_INVALID",
      JSON.stringify(override)
    );
  }
});

test("the generator imports no I/O, network, clock, or provider module", () => {
  const specifiers = ["probe-scaffold.ts", "probe-scaffold-engines.ts"].flatMap((name) => {
    const source = readFileSync(new URL(`../../packages/workspace/src/init/${name}`, import.meta.url), "utf8");
    assert.doesNotMatch(source, /\bDate\b|process\.|Math\.random|import\(/u, name);
    return ts
      .createSourceFile(name, source, ts.ScriptTarget.Latest)
      .statements.filter(
        (statement) =>
          (ts.isImportDeclaration(statement) || ts.isExportDeclaration(statement)) &&
          statement.moduleSpecifier !== undefined
      )
      .map((statement) => statement.moduleSpecifier.text);
  });
  assert.deepEqual([...new Set(specifiers)].sort(), [
    "../scanner/scanner-primitives.ts",
    "./probe-scaffold-engines.ts",
    "@verchestra/domain"
  ]);
});
